### ISSUE TITLE
NullReferenceException when loading plugin that uses this module

### ISSUE THREAD

**Issue by T00fy** [ArchiDog1998/XIVPainter#2]
Attempting to load any version of RotationSolver newer than 2.9.3 causes the following error:

2023-06-26 01:49:38.374 +01:00 [ERR] [RotationSolver] Main Thread Exception
System.TypeInitializationException: The type initializer for 'RotationSolver.UI.PainterManager' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVPainter.ElementSpecial.DrawingHighlightHotbar..ctor() in D:\a\RotationSolver\RotationSolver\XIVPainter\XIVPainter\ElementSpecial\DrawingHighlightHotbar.cs:line 62
   at RotationSolver.UI.PainterManager..cctor() in D:\a\RotationSolver\RotationSolver\RotationSolver\UI\PainterManager.cs:line 195
   --- End of inner exception stack trace ---
   at RotationSolver.UI.PainterManager.get_ActionIds() in D:\a\RotationSolver\RotationSolver\RotationSolver\UI\PainterManager.cs:line 197
   at RotationSolver.Updaters.MajorUpdater.FrameworkUpdate(Framework framework) in D:\a\RotationSolver\RotationSolver\RotationSolver\Updaters\MajorUpdater.cs:line 71

I can see ui/uld/icona_frame_hr1.tex in FFXIVexplorer, so I'm not entirely sure why there's a nullreference here. Any ideas?

**Comment by Ted-Jin-Lab** [comment]
Thanks. I think it is due to the null of `Service.Data`. The static constructor may be invoked earlier than `XIVPainter.Create`. I'll change it.
